[#5] upgrade guava to latest version : 18.0
version 16.1 or latter required to use compile-testing
(using 14.0.1 make compile-testing code fail with java.lang.NoSuchMethodError: com.google.common.io.ByteSource.wrap([B)Lcom/google/common/io/ByteSource;)